### PR TITLE
Improve: Add value hint for source

### PR DESCRIPTION
**Pull request by laxect**
Improve sources completion.

image

### CODE REVIEW

**Comment by nanozuki** [comment]
@laxect do you want to fix windows build ?

**Comment by laxect** [comment]
> @laxect do you want to fix windows build ?

Seems have no relation with this change?

**Comment by nanozuki** [comment]
> > @laxect do you want to fix windows build ?
> 
> Seems have no relation with this change?

maybe, because of "/" and "\" ? 🤔

**Comment by laxect** [comment]
> > > @laxect do you want to fix windows build ?
> > 
> > Seems have no relation with this change?
> 
> maybe, because of `/` and `\` ? 🤔

Only the gnu build failed... I don't think so.

**Comment by laxect** [comment]
> @laxect do you want to fix windows build ?

Problem disappear now.

**Pull request merged**
